name: Build and Deploy
on:
  push:
    branches:
      - main # change this to your default branch name if it's not 'main'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build:prod

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: dist/chuck-norris-joke-generator/browser # The folder the action should deploy.
          token: ${{ secrets.GH_TOKEN }} # The GitHub token.
